###########
# site.title, site.url, site.author.name

title:   'faceinator'
author:
  name:  'A fully analog implementation of face detector'

########
# more settings
baseurl: /faceinator
markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

